version: '3'
services:
  app: &app_base
    build: "."
    stdin_open: true
    tty: true
    ports:
      - $HTTP_PORT:3000
    command: /bin/sh -c "bundle install && yarn install --check-files && bundle exec rails s -b 0.0.0.0"
    environment:
      RAILS_ENV: $RAILS_ENV
      NODE_ENV: $RAILS_ENV
      # .bundle/config を gitに含めて提供してください
      BUNDLE_APP_CONFIG: ./.bundle
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/var/www/ChaChaCha
      - bundle:/var/www/ChaChaCha/vendor/bundle
      - node-modules:/var/www/ChaChaCha/node_modules
      - packs:/var/www/ChaChaCha/public/packs
    depends_on:
      - postgres
      - redis
  webpack:
    <<: *app_base
    command: /bin/sh -c "bundle install && yarn install --check-files && bin/webpack-dev-server"
    environment:
      NODE_ENV: $RAILS_ENV
      RAILS_ENV: $RAILS_ENV
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - $WEBPACK_PORT:3035
    tty: true
    stdin_open: true
    depends_on:
      - app

  postgres:
    stdin_open: true
    tty: true
    restart: always
    image: postgres:12.2
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:3.2.11
    environment:
      TZ: Asia/Tokyo
    ports:
      - $REDIS_PORT:6379
    command: redis-server --appendonly yes

volumes:
  pgsql-data:
  bundle:
  node-modules:
  packs:
