 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.xdescribe "/arigatonas", type: :request do
  # Arigatona. As you add validations to Arigatona, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Arigatona.create! valid_attributes
      get arigatonas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      arigatona = Arigatona.create! valid_attributes
      get arigatona_url(arigatona)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_arigatona_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      arigatona = Arigatona.create! valid_attributes
      get edit_arigatona_url(arigatona)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Arigatona" do
        expect {
          post arigatonas_url, params: { arigatona: valid_attributes }
        }.to change(Arigatona, :count).by(1)
      end

      it "redirects to the created arigatona" do
        post arigatonas_url, params: { arigatona: valid_attributes }
        expect(response).to redirect_to(arigatona_url(Arigatona.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Arigatona" do
        expect {
          post arigatonas_url, params: { arigatona: invalid_attributes }
        }.to change(Arigatona, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post arigatonas_url, params: { arigatona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested arigatona" do
        arigatona = Arigatona.create! valid_attributes
        patch arigatona_url(arigatona), params: { arigatona: new_attributes }
        arigatona.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the arigatona" do
        arigatona = Arigatona.create! valid_attributes
        patch arigatona_url(arigatona), params: { arigatona: new_attributes }
        arigatona.reload
        expect(response).to redirect_to(arigatona_url(arigatona))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        arigatona = Arigatona.create! valid_attributes
        patch arigatona_url(arigatona), params: { arigatona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested arigatona" do
      arigatona = Arigatona.create! valid_attributes
      expect {
        delete arigatona_url(arigatona)
      }.to change(Arigatona, :count).by(-1)
    end

    it "redirects to the arigatonas list" do
      arigatona = Arigatona.create! valid_attributes
      delete arigatona_url(arigatona)
      expect(response).to redirect_to(arigatonas_url)
    end
  end
end
