 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/roots", type: :request do
  # Root. As you add validations to Root, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Root.create! valid_attributes
      get roots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      root = Root.create! valid_attributes
      get root_url(root)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_root_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      root = Root.create! valid_attributes
      get edit_root_url(root)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Root" do
        expect {
          post roots_url, params: { root: valid_attributes }
        }.to change(Root, :count).by(1)
      end

      it "redirects to the created root" do
        post roots_url, params: { root: valid_attributes }
        expect(response).to redirect_to(root_url(Root.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Root" do
        expect {
          post roots_url, params: { root: invalid_attributes }
        }.to change(Root, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post roots_url, params: { root: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested root" do
        root = Root.create! valid_attributes
        patch root_url(root), params: { root: new_attributes }
        root.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the root" do
        root = Root.create! valid_attributes
        patch root_url(root), params: { root: new_attributes }
        root.reload
        expect(response).to redirect_to(root_url(root))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        root = Root.create! valid_attributes
        patch root_url(root), params: { root: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested root" do
      root = Root.create! valid_attributes
      expect {
        delete root_url(root)
      }.to change(Root, :count).by(-1)
    end

    it "redirects to the roots list" do
      root = Root.create! valid_attributes
      delete root_url(root)
      expect(response).to redirect_to(roots_url)
    end
  end
end
